#!/usr/bin/env zsh
#
# Show manually installed packages on a system.
#

comm -23 <(apt-mark showmanual | sort -u) <(gzip -dc /var/log/installer/initial-status.gz | sed -n 's/^Package: //p' | sort -u)

